<?php

// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 macronom

declare(strict_types=1);

namespace Catenvis;

/**
 * Renders a config/config.php file from a configuration array. Used by
 * bin/setup.php to write the initial configuration.
 *
 * Values are emitted via var_export, so passwords and API tokens are escaped
 * safely no matter what characters they contain; the result is valid PHP that
 * returns the exact array it was given.
 */
final class ConfigWriter {
	/**
	 * Full PHP source of a config file that returns $config.
	 *
	 * @param array<string, mixed> $config
	 */
	public static function render(array $config): string {
		return "<?php\n\n"
			. "declare(strict_types=1);\n\n"
			. "/**\n"
			. " * Catenvis configuration - generated by bin/setup.php.\n"
			. " * See config/config.sample.php for documentation of every option.\n"
			. " *\n"
			. " * @return array<string, mixed>\n"
			. " */\n\n"
			. 'return ' . var_export($config, true) . ";\n";
	}
}
